### PR TITLE
Issue1:Accuracy and Coverage:Simple counts

### PR DESCRIPTION
**Pull request by srnb**
Added class to calculate accuracy and coverage using counts.

### CODE REVIEW

**Comment by yoid2000** [comment]
@srnb 

Some comments:

There is no reason you should be modifying gdaScore.py. (Or if there is, please let me know)

There is also no reason you should be making a copy of it here. There should only be one copy. If there is some problem running your code with the library in the attacks repo, then maybe we need to re-organize the structure.

Likewise there is no reason you should be putting a json config here

You should modify .gitignore so that it does not include any `.db` file.

**Comment by srnb** [comment]
It was my bad, Config files were added by mistake(.dbfile).
Regarding gdaScore.py, I thought of adding exception handling and logs. So I copied it separately for this module and also I assumed these both are different entities. So I copied to this module. There is no problem in running code with a library(attacks repo).

**Comment by yoid2000** [comment]
Exception handling and logs are both great ideas. But the idea then is that we update the version in 'attacks'?

**Comment by srnb** [comment]
Yes. the comment says, But it has code for issue1. Also, I have removed the unused file from the previous commit and log files.

**Pull request merged**
